let indexDatabase = Math.floor(Math.random() * 2);
let indexLine = Math.floor(Math.random() * 100);


function buttonClick() {
    var element = document.getElementById("fly");
    element.classList.toggle("clicked");
    var paragraph = document.getElementById("pCenter");
    paragraph.textContent = "Safe Travels";

}


// var place1 = 'https://lp-cms-production.imgix.net/2021-03/shutterstock_304631102.jpg?auto=format&q=40&ar=16%3A9&fit=crop&w=1946';
// var place2 = 'https://rimage.gnst.jp/livejapan.com/public/article/detail/a/00/02/a0002532/img/basic/a0002532_main.jpg';
// var place3 = "http://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQWXvWyGh1DR7LREnbg2Q0cn2T_QZ4ae85BFM7HPt59V0sY3PwmKcB5VAY5B77xDMm7";
const places = [];
const oneHundreds = [
    ['Turkey', 'Grand Bazaar', 'The Grand Bazaar in Istanbul is one of the largest and oldest covered markets in the world, with 61 covered streets and over 4,000 shops on a total area of 30,700 m², attracting between 250,000 and 400,000 visitors daily.', 'https://en.wikipedia.org/wiki/Grand_Bazaar,_Istanbul', 'https://www.planetware.com/wpimages/2021/03/turkey-istanbul-grand-bazaar-things-to-buy-shopping-tips-lamps-lanterns.jpg']
    , ['United States', 'Grand Canyon', 'Grand Canyon National Park, in Arizona, is home to much of the immense Grand Canyon, with its layered bands of red rock revealing millions of years of geological history.', 'google.com', 'https://morethanjustparks.com/wp-content/uploads/2022/04/grand-canyon1.jpg']
    , ['Thailand', 'Grand Palace', 'The Grand Palace is a complex of buildings at the heart of Bangkok, Thailand. The palace has been the official residence of the Kings of Siam since 1782. The king, his court, and his royal government were based on the grounds of the palace until 1925.', 'https://en.wikipedia.org/wiki/Grand_Palace', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Bangkok_08_-_26_%283167077938%29.jpg/530px-Bangkok_08_-_26_%283167077938%29.jpg']
    , ['Belgium@Grand Place', "The Grand Place or Grote Markt is the central square of Brussels, Belgium. It is surrounded by opulent Baroque guildhalls of the former Guilds of Brussels and two larger edifices; the city's Flamboyant Town Hall, and the neo-Gothic King's House or Bread House building, containing the Brussels City Museum.", 'https://en.wikipedia.org/wiki/Grand_Place', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/37/83/7c/grand-place.jpg?w=1200&h=1200&s=1']
    , ['Australia', 'Great Barrier Reef', "The Great Barrier Reef is the world's largest coral reef system composed of over 2,900 individual reefs and 900 islands stretching for over 2,300 kilometres over an area of approximately 344,400 square kilometres.", 'https://en.wikipedia.org/wiki/Great_Barrier_Reef', 'https://cdn.britannica.com/64/155864-050-34FBD7A2/view-Great-Barrier-Reef-Australia-coast.jpg']
    , ['Belize', 'Great Blue Hole', 'The Great Blue Hole is a giant marine sinkhole off the coast of Belize. It lies near the center of Lighthouse Reef, a small atoll 70 km from the mainland and Belize City. The hole is circular in shape, 318 m across and 124 m deep. It has a surface area of 70,650 square metres.', 'https://en.wikipedia.org/wiki/Great_Blue_Hole', 'https://upload.wikimedia.org/wikipedia/commons/6/61/Great_Blue_Hole.jpg']
    , ['Japan', 'Great Buddha', 'Kōtoku-in is a Buddhist temple of the Jōdo-shū sect, in the city of Kamakura in Kanagawa Prefecture, Japan. Its mountain name is Taiizan, and its common temple name is Shōjōsen-ji.', 'https://en.wikipedia.org/wiki/Kōtoku-in', 'https://upload.wikimedia.org/wikipedia/commons/0/07/JP-kamakura-daibutsu-2.jpg']
    , ['Spain', 'Great Mosque Of Cordoba', 'The Mosque–Cathedral of Córdoba, officially known by its ecclesiastical name, the Cathedral of Our Lady of the Assumption, is the cathedral of the Roman Catholic Diocese of Córdoba dedicated to the Assumption of Mary and located in the Spanish region of Andalusia.', 'https://en.wikipedia.org/wiki/Mosque–Cathedral_of_Córdoba', 'https://cdn.kastatic.org/ka-perseus-images/29685278aeae73f8be6c38006ef70ad4ba041896.jpg']
    , ['Australia', 'Great Ocean Road', 'The Great Ocean Road is an Australian National Heritage listed 240-kilometre stretch of road along the south-eastern coast of Australia between the Victorian cities of Torquay and Allansford.', 'https://en.wikipedia.org/wiki/Great_Ocean_Road', 'https://fullsuitcase.com/wp-content/uploads/2021/11/Great-Ocean-Road-Australia.jpg']
    , ['Egypt', 'The Great Pyramid Of Giza', 'The Great Pyramid of Giza is the largest Egyptian pyramid and the tomb of Fourth Dynasty pharaoh Khufu. Built in the early 26th century BC during a period of around 27 years, the pyramid is the oldest of the Seven Wonders of the Ancient World, and the only one to remain largely intact.', 'https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza', 'https://i.natgeofe.com/n/535f3cba-f8bb-4df2-b0c5-aaca16e9ff31/giza-plateau-pyramids_2x1.jpg']
    , ['Egypt', 'The Great Sphinx', 'The Great Sphinx of Giza is a limestone statue of a reclining sphinx, a mythical creature with the head of a human, and the body of a lion. Facing directly from west to east, it stands on the Giza Plateau on the west bank of the Nile in Giza, Egypt. The face of the Sphinx appears to represent the pharaoh Khafre.', 'https://en.wikipedia.org/wiki/Great_Sphinx_of_Giza', 'https://cdn.britannica.com/85/99185-050-E1110E5C/Great-Sphinx-Giza-Egypt.jpg']
    , ['China', 'The Great Wall Of China', 'The Great Wall of China is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe.', 'https://en.wikipedia.org/wiki/Great_Wall_of_China', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/1200px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg']
    , ['Iceland', 'Gullfoss Waterfall', 'Gullfoss is a waterfall located in the canyon of the Hvítá river in southwest Iceland.', 'https://en.wikipedia.org/wiki/Gullfoss', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Gullfoss_from_the_Air.jpg']
    , ['South Korea', 'Gyeongbokgung Palace', 'Gyeongbokgung, also known as Gyeongbokgung Palace or Gyeongbok Palace, was the main royal palace of the Joseon dynasty. Built in 1395, it is located in northern Seoul, South Korea.', 'https://en.wikipedia.org/wiki/Gyeongbokgung', 'https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/27/71/d0.jpg']
    , ['Turkmenistan', 'Gypjak Mosque', 'Turkmenbashi Ruhy Mosque or Gypjak Mosque is a mosque in Gypjak, Turkmenistan and the resting place for Saparmurat Niyazov, the leader of Turkmenistan from 1985 to 2006. The mosque is located about 7 kilometres west of the capital, Ashgabat, on the M37 highway.', 'https://en.wikipedia.org/wiki/Türkmenbaşy_Ruhy_Mosque', 'https://www.advantour.com/img/turkmenistan/ashgabat/turkmenbashi-ruhy-mosque.jpg']
    , ['Turkey', 'Hagia Sophia', 'Hagia Sophia, officially the Hagia Sophia Grand Mosque, is a mosque and major cultural and historical site in Istanbul, Turkey. Originally a Greek Orthodox church, the site has changed between being a mosque and a museum since the fall of the Byzantine Empire.', 'https://en.wikipedia.org/wiki/Hagia_Sophia', 'https://cdn.britannica.com/03/189803-050-871B95C4/Hagia-Sophia-Istanbul.jpg']
    , ['Iceland', 'Hallgrimskirkja', 'Hallgrímskirkja is a Lutheran parish church in Reykjavík, Iceland. At 74.5 metres tall, it is the largest church in Iceland and among the tallest structures in the country.', 'https://en.wikipedia.org/wiki/Hallgrímskirkja', 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Reykjavik%27s_church.jpg']
    , ['Vietnam', 'Halong Bay', 'Hạ Long Bay, in northeast Vietnam, is known for its emerald waters and thousands of towering limestone islands topped by rainforests. Junk boat tours and sea kayak expeditions take visitors past islands named for their shapes, including Stone Dog and Teapot islets. The region is popular for scuba diving, rock climbing and hiking, particularly in mountainous Cát Bà National Park.', 'google.com', 'https://lp-cms-production.imgix.net/features/2019/04/HalongBay-aa0f7e71a1db.jpg']
    , ['Vietnam', 'Hanoi', 'Hanoi, the capital of Vietnam, is known for its centuries-old architecture and a rich culture with Southeast Asian, Chinese and French influences. At its heart is the chaotic Old Quarter, where the narrow streets are roughly arranged by trade. There are many little temples, including Bach Ma, honoring a legendary horse, plus Đồng Xuân Market, selling household goods and street food.', 'google.com', 'https://a.cdn-hotels.com/gdcs/production144/d1394/a304783d-6dc9-4bb2-9239-d124a16a154e.jpg']
    , ['Cuba', 'Havana', 'Havana is Cuba’s capital city. Spanish colonial architecture in its 16th-century Old Havana core includes the Castillo de la Real Fuerza, a fort and maritime museum. The National Capitol Building is an iconic 1920s landmark. Also in Old Havana is the baroque Catedral de San Cristóbal and Plaza Vieja, whose buildings reflect the city’s vibrant architectural mix.', 'google.com', 'https://cdn.britannica.com/33/76033-050-7E290193/Havana.jpg']
    , ['Hawaii', 'Hawaiʻi Volcanoes National Park', "Hawaii Volcanoes National Park is on Hawaii Island (the Big Island). At its heart are the Kīlauea and Mauna Loa active volcanoes. The Crater Rim Drive passes steam vents and the Jaggar Museum, which features volcanology exhibits and a viewpoint overlooking Halema'uma'u Crater. Thick ferns mark the entrance to the Thurston Lava Tube (Nāhuku). The Chain of Craters Road weaves over lava. Trails crisscross the park.", 'google.com', 'https://i.natgeofe.com/k/4ab71fc1-36e0-49c8-a382-fd02ee37a1a5/Hawaii-flowing-lava_16x9.jpg?w=1200']
    , ['India', 'Hawa Mahal', "The Hawa Mahal is a palace in the city of Jaipur, India. Built from red and pink sandstone, it is on the edge of the City Palace, Jaipur, and extends to the Zenana, or women's chambers.", 'https://en.wikipedia.org/wiki/Hawa_Mahal', 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Hawa_Mahal_east_facade_%2814-07-2022%29.jpg']
    , ['Finland', 'Helsinki Cathedral', 'Helsinki Cathedral is the Finnish Evangelical Lutheran cathedral of the Diocese of Helsinki, located in the neighborhood of Kruununhaka in the centre of Helsinki, Finland at the Senate Square. The church was originally built from 1830–1852 as a tribute to the Grand Duke of Finland, Tsar Nicholas I of Russia.', 'https://en.wikipedia.org/wiki/Helsinki_Cathedral', 'https://images.mapsofworld.com/allwonders/helsinki-cathedral.jpg']
    , ['Chile', 'Hills of Valparaíso', 'Hills of Valparaíso are the predominant geographical feature that rise above the main port area of Valparaíso in Chile. In many cases the hills have communities tied to the name of the specific hills.', 'https://en.wikipedia.org/wiki/Hills_of_Valparaíso', 'https://previews.123rf.com/images/lindrik/lindrik1602/lindrik160200154/52824423-colorful-buildings-on-the-hills-of-the-city-of-valparaiso-chile.jpg']
    , ['Japan', 'Himeji Castle', 'Himeji Castle is a hilltop Japanese castle complex situated in the city of Himeji which is located in the Hyōgo Prefecture of Japan.', 'https://en.wikipedia.org/wiki/Himeji_Castle', 'https://a.cdn-hotels.com/gdcs/production73/d1285/6a9f1ee4-320c-4452-9efc-7b20d9b33d45.jpg?impolicy=fcrop&w=800&h=533&q=medium']
    , ['Japan', 'Hiroshima Peace Memorial', 'The Hiroshima Peace Memorial (Genbaku Dome) was the only structure left standing in the area where the first atomic bomb exploded on 6 August 1945. Through the efforts of many people, including those of the city of Hiroshima, it has been preserved in the same state as immediately after the bombing. Not only is it a stark and powerful symbol of the most destructive force ever created by humankind; it also expresses the hope for world peace and the ultimate elimination of all nuclear weapons.', 'https://whc.unesco.org/en/list/775/', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/20181111_Hiroshima_Memorial_Cenotaph-1.jpg/1200px-20181111_Hiroshima_Memorial_Cenotaph-1.jpg']
    , ['New Zealand', 'Hobbiton in Matamata', 'The Hobbiton Movie Set is a significant location used for The Lord of the Rings film trilogy and The Hobbit film trilogy.', 'https://en.wikipedia.org/wiki/Hobbiton_Movie_Set', 'https://www.newzealand.com/assets/Operator-Database/3fc2b5d066/img-1536162697-1401-3228-p-95B514EA-DAAA-9CB0-6839532442B3132A-2544003__aWxvdmVrZWxseQo_CropResizeWzk0MCw1MzAsNzUsImpwZyJd.jpg']
    , ['United States', 'Hollywood Sign', 'The Hollywood Sign is an American landmark and cultural icon overlooking Hollywood, Los Angeles, California. It is situated on Mount Lee, in the Beachwood Canyon area of the Santa Monica Mountains.', 'https://en.wikipedia.org/wiki/Hollywood_Sign', 'https://griffithobservatory.org/wp-content/uploads/2021/12/cameron-venti-6QDvwq2Fjsc-unsplash-scaled.jpg']
    , ['Hong Kong', 'Hong Kong', "Hong Kong, officially the Hong Kong Special Administrative Region of the People's Republic of China, is a city and special administrative region of China on the eastern Pearl River Delta in South China.", 'https://en.wikipedia.org/wiki/Hong_Kong', 'https://www.datacenterknowledge.com/sites/datacenterknowledge.com/files/styles/article_featured_retina/public/EBHM39.jpg?itok=PUzBwD5h']
    , ['Brazil', 'Iguazu Falls', 'The Iguazu (also called Iguassu) Falls are composed of 275 separate cascades, which make it the largest broken waterfall in the world. Made up of a chain of waterfalls that are fed by the Iguazu River, this powerful phenomenon sits on the border of Argentina and Brazil.', 'https://www.andbeyond.com/advice/south-america/argentina/iguazu-falls/visit-iguazu-falls/', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Cataratas.jpg/800px-Cataratas.jpg']
    , ['Iraq', 'Imam Husayn Shrine', 'The Imam Husayn Shrine is the mosque and burial site of Husayn ibn Ali, the third Imam of Shia Islam, in the city of Karbala, Iraq.', 'https://en.wikipedia.org/wiki/Imam_Husayn_Shrine', 'https://upload.wikimedia.org/wikipedia/commons/d/d6/Imam_Husayn_Shrine.jpg']
    , ['Iran', 'Imam Reza Holy Shrine', 'The Imam Reza shrine in Mashhad, Iran, is a complex which contains the mausoleum of Imam Reza, the eighth Imam of Twelver Shias. It is the largest mosque in the world by area.', 'https://en.wikipedia.org/wiki/Imam_Reza_shrine', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/86/55/a9/great-court.jpg?w=1200&h=1200&s=1']
    , ['Iran', 'Naqsh-e Jahan Square', "Naqsh-e Jahan Square, also known as the Shah Square prior to 1979, is a square situated at the center of Isfahan, Iran. Constructed between 1598 and 1629, it is now an important historical site, and one of UNESCO's World Heritage Sites. It is 160 metres wide by 560 metres long.", 'https://en.wikipedia.org/wiki/Naqsh-e_Jahan_Square', 'https://www.irantravelingcenter.com/wp-content/uploads/2014/09/isfahan.iran-traveling-center.Imam-square.jpg']
    , ['United States', 'Independence Hall', "Independence Hall is a historic civic building in Philadelphia, Pennsylvania in which both the United States Declaration of Independence and the United States Constitution were debated and adopted by America's Founding Fathers.", 'https://en.wikipedia.org/wiki/Independence_Hall', 'https://www.nps.gov/inde/planyourvisit/images/Hall-and-Wings-960-X-480_1.jpg?maxwidth=1200&maxheight=1200&autorotate=false']
    , ['British Columbia', 'Inukshuk', "Inukshuk is an outdoor inuksuk by Alvin Kanak, installed at Vancouver's English Bay, in British Columbia.", 'https://en.wikipedia.org/wiki/Inukshuk_(Kanak)', 'https://westendbia.com/media/2020/07/Inukshuk-by-the-Beach-5843-explorewithcarl-400x267.jpg']
    , ['Brazil', 'Ipanema Beach', 'Long, popular stretch of beach known for sunbathing, along with soccer & volleyball.', 'google.com', 'https://lp-cms-production.imgix.net/2019-06/GettyImages-147189497_medium.jpg']
    , ['Japan', 'Itsukushima Shrine', 'Itsukushima Shrine is a Shinto shrine on the island of Itsukushima, best known for its "floating" torii gate. It is in the city of Hatsukaichi in Hiroshima Prefecture in Japan, accessible from the mainland by ferry at Miyajimaguchi Station.', 'https://en.wikipedia.org/wiki/Itsukushima_Shrine', 'https://gaijinpot.scdn3.secure.raxcdn.com/app/uploads/sites/6/2016/01/Miyajima-Floating-shrine.jpg']
    , ['Indonesia', 'Java', 'Java, lying between Sumatra and Bali, is a volcano-dotted island that’s at the geographic and economic center of Indonesia, and home to more than half its people. Java’s largest city is modern, sprawling Jakarta, the nation’s capital. It’s home to the expansive National Museum, an old town (Kota Tua) with Dutch colonial buildings, as well as upscale hotels and shopping malls.', 'google.com', 'https://img.theculturetrip.com/wp-content/uploads/2018/04/shutterstock_594209144-by-wathit-h.jpg']
    , ['India', 'K2', 'K2, at 8,611 metres (28,251 ft) above sea level, is the second-highest mountain on Earth, after Mount Everest (at 8,849 metres (29,032 ft)).[3] It lies in the Karakoram range, partially in the Gilgit-Baltistan region of Pakistan-administered Kashmir and partially in a China-administered territory of the Kashmir region included in the Taxkorgan Tajik Autonomous County of Xinjiang.', 'https://en.wikipedia.org/wiki/K2', 'http://cdn.cnn.com/cnnnext/dam/assets/220804075925-k2-moutain-pakistan.jpg']
    , ['Asia', 'Kashmir Valley', 'The Kashmir Valley, also known as the Vale of Kashmir, is an intermontane valley concentrated in the Kashmir Division of the Indian-administered union territory of Jammu and Kashmir. The valley is bounded on the southwest by the Pir Panjal Range and on the northeast by the main Himalayas range.', 'https://en.wikipedia.org/wiki/Kashmir_Valley', 'https://media.tacdn.com/media/attractions-splice-spp-674x446/06/74/9d/4c.jpg']
    , ['Tanzania', 'Mount Kilimanjaro', 'Mount Kilimanjaro is a dormant volcano in Tanzania. It has three volcanic cones: Kibo, Mawenzi, and Shira. It is the highest mountain in Africa and the highest single free-standing mountain above sea level in the world: 5,895 metres above sea level and about 4,900 metres above its plateau base.', 'https://en.wikipedia.org/wiki/Mount_Kilimanjaro', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Mt._Kilimanjaro_12.2006.JPG/1200px-Mt._Kilimanjaro_12.2006.JPG']
    , ['Indonesia', 'Komodo', 'Komodo island, part of the Lesser Sunda chain of Indonesian islands, is the rugged habitat of the 3m-long Komodo dragon monitor lizard. Komodo National Park covers the entire region and is home to more than 4,000 dragons, and is made up of rusty-red volcanic hills, savannah and forests. Its surrounding waters of seagrass beds, mangrove shrublands and coral reefs are famous for diving.', 'google.com', 'https://media.cntraveler.com/photos/5da4e49d4b1e400008203733/16:9/w_2560%2Cc_limit/Komodo-Island_GettyImages-919467902.jpg']
    , ['South Africa', 'Kruger National Park', 'Kruger National Park, in northeastern South Africa, is one of Africa’s largest game reserves. Its high density of wild animals includes the Big 5: lions, leopards, rhinos, elephants and buffalos. Hundreds of other mammals make their home here, as do diverse bird species such as vultures, eagles and storks. Mountains, bush plains and tropical forests are all part of the landscape.', 'google.com', 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Kruger_Zebra.JPG']
    , ['Kuwait', 'Kuwait Towers', 'The Kuwait Towers are a group of three thin towers in Kuwait City, standing on a promontory into the Persian Gulf. They were the sixth, and last, group in the larger Kuwait Water Towers system of 34 towers, and were built in a style considerably different from the other five groups.', 'https://en.wikipedia.org/wiki/Kuwait_Towers', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/88/87/81/photo6jpg.jpg?w=1200&h=1200&s=1']
    , ['Guatemala', 'Lake Atitlán', 'Lake Atitlán is a body of water in a massive volcanic crater in Guatemala’s southwestern highlands. Ringed by steep, verdant hills, it’s known for its Mayan villages and volcanoes with striking pointed cones. The busy town of Panajachel, where vendors sell traditional textiles, is a popular gateway to the lake. On a former coffee plantation, the Atitlán nature reserve offers trails and a butterfly garden.', 'google.com', 'https://www.roadaffair.com/wp-content/uploads/2017/10/lake-atitlan-guatemala-shutterstock_189649244-1024x679.jpg']
    , ['Russia', 'Lake Baikal', 'Lake Baikal is an ancient, massive lake in the mountainous Russian region of Siberia, north of the Mongolian border. Considered the deepest lake in the world, it’s circled by a network of hiking paths called the Great Baikal Trail. The village of Listvyanka, on its western shoreline, is a popular starting point for summertime wildlife-spotting tours, plus wintertime ice-skating and dog sledding.', 'google.com', 'https://images.theconversation.com/files/252656/original/file-20190107-32133-6lq46u.jpg?ixlib=rb-1.1.0&rect=0%2C7%2C4987%2C2493&q=45&auto=format&w=1356&h=668&fit=crop']
    , ['Slovenia', 'Lake Bled', 'Lake Bled is a lake in the Julian Alps of the Upper Carniolan region of northwestern Slovenia, where it adjoins the town of Bled. The area is a tourist destination. The lake is 35 km from Ljubljana International Airport and 55 km from the capital city, Ljubljana. Lake Bled is 4.2 km from the Lesce–Bled train station', 'https://en.wikipedia.org/wiki/Lake_Bled', 'https://s27363.pcdn.co/wp-content/uploads/2018/10/Bled-Island.jpg.optimal.jpg']
    , ['Senegal', 'Lake Retba', 'Lac Rose lies north of the Cap Vert peninsula of Senegal, some 30 km north-east of the capital, Dakar, in northwest Africa. It is named for its pink waters caused by Dunaliella salina algae and is known for its high salt content, up to 40% in some areas.', 'https://en.wikipedia.org/wiki/Lake_Retba', 'https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/39/aa/2a.jpg']
    , ['United States', 'Las Vegas Strip', 'Lined with upscale casino hotels, the neon-soaked Strip is quintessential Las Vegas. As well as gambling floors, the vast hotel complexes house a variety of shops, restaurants (ranging from mainstream to high-end), and performance venues for music, comedy and circus-style acts. Attractions like the soaring, choreographed Fountains of Bellagio and the High Roller observation wheel draw crowds.', 'google.com', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/01/00/2b/the-strip.jpg?w=1200&h=1200&s=1']
    , ['Italy', 'Leaning Tower Of Pisa', 'The Leaning Tower of Pisa, or simply, the Tower of Pisa, is the campanile, or freestanding bell tower, of Pisa Cathedral. It is known for its nearly four-degree lean, the result of an unstable foundation.', 'https://en.wikipedia.org/wiki/Leaning_Tower_of_Pisa', 'https://cdn.britannica.com/88/80588-050-8D944BFE/Leaning-Tower-of-Pisa-Italy.jpg']
    , ['China', 'Li Jiang', 'The Li River or Li Jiang is the name for the upper reaches of the Gui River in northwestern Guangxi, China. It is part of the Xijiang River system in the Pearl River Basin.', 'https://en.wikipedia.org/wiki/Li_River', 'https://upload.wikimedia.org/wikipedia/commons/2/21/%E6%BC%93%E6%B1%9F%E5%B1%B1%E6%B0%B4.jpg']
    , ['Scotland', 'Loch Ness', 'Loch Ness is a large freshwater loch in the Scottish Highlands extending for approximately 37 kilometres southwest of Inverness. It takes its name from the River Ness, which flows from the northern end.', 'https://en.wikipedia.org/wiki/Loch_Ness', 'https://ichef.bbci.co.uk/news/976/cpsprodpb/2F0A/production/_108624021_gettyimages-478736791.jpg']
    , ['France', 'Loire Valley', 'The Loire Valley, spanning 280 kilometres, is a valley located in the middle stretch of the Loire river in central France, in both the administrative regions Pays de la Loire and Centre-Val de Loire. The area of the Loire Valley comprises about 800 square kilometres.', 'https://en.wikipedia.org/wiki/Loire_Valley', 'https://www.planetware.com/photos-large/F/france-loire-valley-chateau-chambord.jpg']
    , ['India', 'Lotus Temple', 'The Lotus Temple, located in Delhi, India, is a Baháʼí House of Worship that was dedicated in December 1986. Notable for its flowerlike shape, it has become a prominent attraction in the city. Like all other Bahá’í Houses of Worship, the Lotus Temple is open to all, regardless of religion or any other qualification.', 'https://en.wikipedia.org/wiki/Lotus_Temple', 'https://cdn.britannica.com/67/156667-050-62285333/Lotus-Temple-New-Delhi-India.jpg']
    , ['France', 'Louvre Museum', "The Louvre, or the Louvre Museum, is the world's most-visited museum, and a historic landmark in Paris, France. It is the home of some of the best-known works of art, including the Mona Lisa and the Venus de Milo.", 'https://en.wikipedia.org/wiki/Louvre', 'https://cdn.britannica.com/02/121002-050-92DB902F/Louvre-Museum-pyramid-Paris-Pei-IM.jpg']
    , ['Egypt', 'Luxor Temple', 'The Luxor Temple is a large Ancient Egyptian temple complex located on the east bank of the Nile River in the city today known as Luxor and was constructed approximately 1400 BCE. In the Egyptian language it was known as ipet resyt, "the southern sanctuary".', 'https://en.wikipedia.org/wiki/Luxor_Temple', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Luxor-Tempel_Pylon_08.jpg/1200px-Luxor-Tempel_Pylon_08.jpg']
    , ['Peru', 'Machu Picchu', 'Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. Built in the 15th century and later abandoned, it’s renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar, intriguing buildings that play on astronomical alignments and panoramic views. Its exact former use remains a mystery.', 'google.com', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1200px-Machu_Picchu%2C_Peru.jpg']
    , ['Madagascar', 'Madagascar', "Madagascar, officially the Republic of Madagascar, is an island country in the Indian Ocean, approximately 400 kilometres off the coast of East Africa across the Mozambique Channel. At 592,800 square kilometres Madagascar is the world's second-largest island country, after Indonesia.", 'https://en.wikipedia.org/wiki/Madagascar', 'https://www.state.gov/wp-content/uploads/2018/11/Madagascar-e1555939583916-2500x1406.jpg']
    , ['Spain', 'Madrid Palace', 'The Royal Palace of Madrid (Spanish: Palacio Real de Madrid) is the official residence of the Spanish royal family at the city of Madrid, although now used only for state ceremonies. The palace has 135,000 m2 (1,450,000 sq ft) of floor space and contains 3,418 rooms.', 'https://en.wikipedia.org/wiki/Royal_Palace_of_Madrid', 'https://images.musement.com/cover/0096/36/thumb_9535685_cover_header.jpeg?q=50&fit=crop&auto=format&w=1024&h=400']
    , ['Australia', 'Manly Beach', 'Manly Beach is a beach situated among the Northern Beaches of Sydney, Australia, in Manly, New South Wales. From north to south, the three main sections are Queenscliff, North Steyne, and South Steyne.', 'https://en.wikipedia.org/wiki/Manly_Beach', 'https://www.sydney.com/sites/sydney/files/styles/open_graph/public/2022-05/164678-Desktop.jpg?itok=S4fCJqAn']
    , ['Germany', 'Marienplatz', "Marienplatz is a central square in the city centre of Munich, Germany. It has been the city's main square since 1158.", 'https://en.wikipedia.org/wiki/Marienplatz', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Rathaus_and_Marienplatz_from_Peterskirche_-_August_2006.jpg/800px-Rathaus_and_Marienplatz_from_Peterskirche_-_August_2006.jpg']
    , ['Morocco', 'The Souks Of Marrakech', 'The souks of Marrakech are often a highlight for any traveller. Indeed, the bustling atmosphere, the bargains, the thrill of haggling and the assault on the senses is often a big part of the reason why people take a trip to Morocco’s Red City.', 'https://theculturetrip.com/africa/morocco/articles/an-essential-guide-to-marrakeshs-souks/', 'https://img.theculturetrip.com/450x/smart/wp-content/uploads/2021/05/marrakech-medina-jemaa-el-fna-square-fb64hw.jpg']
    , ['Kenya', 'Maasai Mara National Reserve', 'Maasai Mara National Reserve is an area of preserved savannah wilderness in southwestern Kenya, along the Tanzanian border. Its animals include lions, cheetahs, elephants, zebras and hippos. Wildebeest traverse its plains during their annual migration. The landscape has grassy plains and rolling hills, and is crossed by the Mara and Talek rivers. The area nearby is dotted with villages (enkangs) of Maasai people.', 'google.com', 'https://www.micato.com/wp-content/uploads/2018/09/maasai-mara-8.jpg']
    , ['Japan', 'Matsumoto Castle', 'Matsumoto Castle, originally known as Fukashi Castle, is one of Japan\'s premier historic castles, along with Himeji and Kumamoto. The building is also known as the "Crow Castle" due to its black exterior. It was the seat of Matsumoto Domain under the Edo Period Tokugawa shogunate.', 'https://en.wikipedia.org/wiki/Matsumoto_Castle', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Matsumoto_Castle05s5s4592.jpg/1200px-Matsumoto_Castle05s5s4592.jpg']
    , ['Kazakhstan', 'Mausoleum Of Khoja Ahmed Yasawi', 'The Mausoleum of Khawaja Ahmed Yasawi is a mausoleum in the city of Turkestan, in southern Kazakhstan. The structure was commissioned in 1389 by Timur, who ruled the area as part of the expansive Timurid Empire, to replace a smaller 12th-century mausoleum of the famous Turkic poet and Sufi mystic, Khoja Ahmed Yasawi.', 'https://en.wikipedia.org/wiki/Mausoleum_of_Khoja_Ahmed_Yasawi', 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Mausoleum_of_Khoja_Ahmed_Yasawi_in_Hazrat-e_Turkestan%2C_Kazakhstan.jpg']
    , ['Saudi Arabia', 'Mecca', 'Mecca, in a desert valley in western Saudi Arabia, is Islam’s holiest city, as it’s the birthplace of the Prophet Muhammad and the faith itself. Only Muslims are allowed in the city, with millions arriving for the annual Hajj (pilgrimage). Dating from the 7th century, the central Masjid al-Haram (Sacred Mosque) surrounds the Kaaba, the cloth-covered cubic structure that’s Islam’s most sacred shrine.', 'google.com', 'https://www.google.com/search?q=Mecca&client=opera-gx&hs=Xxo&hl=en&sxsrf=ALiCzsYX5eQyfC0cKY0Rz-kcW5IIQXI0gg:1664663139960&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjD2oK5icD6AhULAzQIHVNdDZ0Q_AUoAXoECAIQAw&biw=1082&bih=1077&dpr=1.13']
    , ['Greece', 'Meteora Greece', 'The Meteora is a rock formation in central Greece hosting one of the largest and most precipitously built complexes of Eastern Orthodox monasteries, second in importance only to Mount Athos. The six monasteries are built on immense natural pillars and hill-like rounded boulders that dominate the local area.', 'https://en.wikipedia.org/wiki/Meteora', 'https://trekhunt.com/en/content/images/size/w1600/2020/11/meteora-1.webp']
    , ['Italy', 'Milan Cathedral', 'Milan Cathedral, or Metropolitan Cathedral-Basilica of the Nativity of Saint Mary, is the cathedral church of Milan, Lombardy, Italy. Dedicated to the Nativity of St Mary, it is the seat of the Archbishop of Milan, currently Archbishop Mario Delpini.', 'https://en.wikipedia.org/wiki/Milan_Cathedral', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Milan_Cathedral_from_Piazza_del_Duomo.jpg/1200px-Milan_Cathedral_from_Piazza_del_Duomo.jpg']
    , ['New Zealand', 'Milford Sound', 'Milford Sound is a fiord in the southwest of New Zealand’s South Island. It’s known for towering Mitre Peak, plus rainforests and waterfalls like Stirling and Bowen falls, which plummet down its sheer sides. The fiord is home to fur seal colonies, penguins and dolphins. Milford Discovery Centre and Underwater Observatory offers views of rare black coral and other marine life. Boat tours are a popular way to explore.', 'google.com', 'https://www.telegraph.co.uk/content/dam/Travel/2018/December/Milford-Sound-GettyImages-875331434.jpg']
    , ['Afghanistan', 'Minaret Of Jam', 'The Minaret of Jam is a UNESCO World Heritage Site in western Afghanistan. It is located in a remote and nearly inaccessible region of the Shahrak District, Ghor Province, next to the Hari River.', 'https://en.wikipedia.org/wiki/Minaret_of_Jam', 'https://upload.wikimedia.org/wikipedia/commons/7/74/Minaret_of_jam_2009_ghor.jpg']
    , ['United States', 'Mississippi River', 'The Mississippi River is the second-longest river and chief river of the second-largest drainage system in North America, second only to the Hudson Bay drainage system.', 'https://en.wikipedia.org/wiki/Mississippi_River', 'https://www.treehugger.com/thmb/7NdlkyXEyZcEFO2xj3__azU4BII=/4002x2620/filters:fill(auto,1)/mississippi-river-at-dawn--148562470-79f2d777aef64843a6c8fe70c7ce1cb1.jpg']
    , ['Easter Island', 'Moai', "Moai or moʻai are monolithic human figures carved by the Rapa Nui people on Easter Island in eastern Polynesia between the years 1250 and 1500. Nearly half are still at Rano Raraku, the main moai quarry, but hundreds were transported from there and set on stone platforms called ahu around the island's perimeter.", 'https://en.wikipedia.org/wiki/Moai', 'https://cdn.theculturetrip.com/wp-content/uploads/2017/05/5414262685_2b35803f5f_b-1024x768.jpg']
    , ['France', 'Mont Saint-Michel', "Mont-Saint-Michel is a tidal island and mainland commune in Normandy, France. The island lies approximately one kilometre off the country's north-western coast, at the mouth of the Couesnon River near Avranches and is 7 hectares in area.", 'https://en.wikipedia.org/wiki/Mont-Saint-Michel', 'https://upload.wikimedia.org/wikipedia/commons/7/78/Mont-Saint-Michel_vu_du_ciel.jpg']
    , ['Italy', 'Mount Etna', 'Mount Etna, or simply Etna, is an active stratovolcano on the east coast of Sicily, Italy, in the Metropolitan City of Catania, between the cities of Messina and Catania. It lies above the convergent plate margin between the African Plate and the Eurasian Plate.', 'https://en.wikipedia.org/wiki/Mount_Etna', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Mt_Etna_and_Catania1.jpg']
    , ['United States', 'Mount Rushmore National Memorial', "Mount Rushmore National Memorial is a massive sculpture carved into Mount Rushmore in the Black Hills region of South Dakota. Completed in 1941 under the direction of Gutzon Borglum and his son Lincoln, the sculpture's roughly 60-ft.-high granite faces depict U.S. presidents George Washington, Thomas Jefferson, Theodore Roosevelt and Abraham Lincoln. The site also features a museum with interactive exhibits.", 'google.com', 'https://interactive.wttw.com/sites/default/files/Monuments_6_Mount-Rushmore_Wolforth.jpg']
    , ['China', 'Museum of Qin Terracotta Warriors and Horses West Gate', 'The Terracotta Army is a collection of terracotta sculptures depicting the armies of Qin Shi Huang, the first emperor of China. It is a form of funerary art buried with the emperor in 210–209 BCE with the purpose of protecting the emperor in his afterlife.', 'https://en.wikipedia.org/wiki/Terracotta_Army', 'https://travelchinawith.me/wp-content/uploads/2012/04/Museum-of-Qin-Terracotta-Warriors-and-Horses.jpg']
    , ['Africa', 'Namib Desert', 'The Namib is a coastal desert in Southern Africa. The name Namib is of Khoekhoegowab origin and means "vast place".', 'https://en.wikipedia.org/wiki/Namib', 'https://cdn.britannica.com/64/94364-050-9B783F3B/Sand-dunes-vegetation-Sossusvlei-Namibia-Namib-desert.jpg']
    , ['United States', 'Napa County', "Napa County is north of San Francisco, in California. It's known for hundreds of hillside vineyards in the Napa Valley wine region. In the city of Napa, Oxbow Public Market features regional gourmet food. The Napa Valley Wine Train is a vintage locomotive and traveling restaurant running through the valley. Northwest of Napa is Yountville, a town known for high-end restaurants and sparkling wine.", 'google.com', 'https://afar.brightspotcdn.com/dims4/default/fcf986d/2147483647/strip/false/crop/1920x1279+0+0/resize/1486x990!/quality/90/?url=https%3A%2F%2Fafar-media-production-web.s3.amazonaws.com%2Fbrightspot%2Ffe%2Ff0%2F1c57ac4c12ed95b4066bc7a72862%2Foriginal-scenic-twomey-lazy-creek-vineyard-72.jpg']
    , ['United States', 'Navy Pier', 'Navy Pier is a 3,300-foot-long pier on the shoreline of Lake Michigan, located in the Streeterville neighborhood of the Near North Side community area in Chicago, Illinois, United States', 'https://en.wikipedia.org/wiki/Navy_Pier', 'https://lp-cms-production.imgix.net/2019-06/a63949fe532d4dd8ca9f16822984afcc-navy-pier.jpg']
    , ['Germany', 'Neuschwanstein Castle', 'Neuschwanstein Castle is a 19th-century historicist palace on a rugged hill above the village of Hohenschwangau near Füssen in southwest Bavaria, Germany. The palace was commissioned by King Ludwig II of Bavaria as a retreat and in honour of Richard Wagner.', 'https://en.wikipedia.org/wiki/Neuschwanstein_Castle', 'https://www.travelandleisure.com/thmb/pZ7QQDocW4IXphhIeDR9nmtiic4=/1333x1000/smart/filters:no_upscale()/01-neuschwanstein-castle-bavaria-NEUSCHWANSTEIN0417-273a040698f24fc1ac22e717bb3f1f0c.jpg']
    , ['Tanzania', 'Ngorongoro Crater Conservation Area', 'Ngorongoro Conservation Area is in northern Tanzania. It’s home to the vast, volcanic Ngorongoro Crater and “big 5” game (elephant, lion, leopard, buffalo, rhino). Huge herds of wildebeests and zebras traverse its plains during their annual migration. Livestock belonging to the semi-nomadic Maasai tribe graze alongside wild animals. Hominin fossils found in the Olduvai Gorge date back millions of years.', 'google.com', 'https://www.tripsavvy.com/thmb/N00vVSNQ5VZl-HOYn7RkPMIYjoM=/3782x2127/smart/filters:no_upscale()/GettyImages-148679836-5b03d89030371300373c5135.jpg']
    , ['United States', 'Niagara Falls', 'Niagara Falls is a group of three waterfalls at the southern end of Niagara Gorge, spanning the border between the province of Ontario in Canada and the state of New York in the United States. The largest of the three is Horseshoe Falls, which straddles the international border of the two countries.', 'https://en.wikipedia.org/wiki/Niagara_Falls', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/3Falls_Niagara.jpg']
    , ['Norway', 'North Cape', 'North Cape is a cape on the northern coast of the island of Magerøya in Northern Norway. The cape is in Nordkapp Municipality in Troms og Finnmark county, Norway.', 'https://en.wikipedia.org/wiki/North_Cape_(Norway)', 'https://www.hurtigruten.com/globalassets/photos/destinations/norway/attractions/north-cape/north-cape-norway_orjan_bertelsen.jpg?width=1900&height=950&center=0.43,0.56&transform=DownResizeCrop']
    , ['North Pole', 'North Pole', "The North Pole, also known as the Geographic North Pole or Terrestrial North Pole, is the point in the Northern Hemisphere where the Earth's axis of rotation meets its surface. It is called the True North Pole to distinguish from the Magnetic North Pole.", 'https://en.wikipedia.org/wiki/North_Pole', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/aerial-view-of-snowcapped-mountains-against-sky-royalty-free-image-1575402338.jpg']
    , ['Norway', 'Norwegian Fjords', 'With more than1,000 fjords around the country, 10 of which are frequented regularly by cruise ships, it’s not surprising that tourists wonder where to go and which fjords to see.', 'https://www.visitnorway.com/things-to-do/nature-attractions/fjords/the-fjords-explained/', 'https://blog-assets.busbud.com/wp-content/uploads/2019/11/Sunnylvsfjorden-fjord-canyon.png']
    , ['France', 'Notre Dame Cathedral', 'Notre-Dame de Paris, referred to simply as Notre-Dame, is a medieval Catholic cathedral on the Île de la Cité, in the 4th arrondissement of Paris. The cathedral, dedicated to the Virgin Mary, is considered one of the finest examples of French Gothic architecture.', 'https://en.wikipedia.org/wiki/Notre-Dame_de_Paris', 'https://cdn.britannica.com/85/83885-050-9CDCFEA9/Notre-Dame-de-Paris-France.jpg']
    , ['Kazakhstan', 'Astana', 'Astana, previously known as Akmolinsk, Tselinograd, Akmola and most recently Nur-Sultan, is the capital city of Kazakhstan.', 'https://en.wikipedia.org/wiki/Astana', 'https://cdn.britannica.com/65/89765-050-50F5F6C0/Nursultan-Kazakhstan.jpg']
    , ['Denmark', 'Nyhavn', 'Nyhavn is a 17th-century waterfront, canal and entertainment district in Copenhagen, Denmark. Stretching from Kongens Nytorv to the harbour front just south of the Royal Playhouse, it is lined by brightly coloured 17th and early 18th century townhouses and bars, cafes and restaurants.', 'https://en.wikipedia.org/wiki/Nyhavn', 'https://files.guidedanmark.org/files/382/134124_Nyhavn_Photo-Thomas-Hyrup-Christensen.jpg.jpg']
    , ['Botswana', 'Okavango Delta', "The Okavango Delta is a vast inland river delta in northern Botswana. It's known for its sprawling grassy plains, which flood seasonally, becoming a lush animal habitat. The Moremi Game Reserve occupies the east and central areas of the region. Here, dugout canoes are used to navigate past hippos, elephants and crocodiles. On dry land, wildlife includes lions, leopards, giraffes and rhinos.", 'google.com', 'https://www.andbeyond.com/wp-content/uploads/sites/5/aerial-view-of-the-okavango-delta-channels-and-landscape.jpg']
    , ['Peru', 'Ollantaytambo', "Ollantaytambo is a village in the Sacred Valley of south Peru, set on the Urubamba River amid snow-capped mountains. It's known for the Ollantaytambo ruins, a massive Inca fortress with large stone terraces on a hillside. Major sites within the complex include the huge Sun Temple and the Princess Baths fountain. The village's old town is an Inca-era grid of cobblestoned streets and adobe buildings.", 'google.com', 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Town_of_Ollantaytambo.jpg']
    , ['China', 'Oriental Pearl Tower', 'The Oriental Pearl Radio & Television Tower is a TV tower in Shanghai. Its location at the tip of Lujiazui in the Pudong New Area by the side of Huangpu River, opposite The Bund, makes it a distinct landmark in the area. Its principal designers were Jiang Huan Chen, Lin Benlin, and Zhang Xiulin.', 'https://en.wikipedia.org/wiki/Oriental_Pearl_Tower', 'https://data.travelchinaguide.com/images/tickets/20190822110729.jpg']
    , ['Norway', 'Oslo Opera House', 'The Oslo Opera House (Norwegian: Operahuset) is the home of the Norwegian National Opera and Ballet, and the national opera theatre in Norway. The building is situated in the Bjørvika neighbourhood of central Oslo, at the head of the Oslofjord.', 'https://en.wikipedia.org/wiki/Oslo_Opera_House', 'http://res.cloudinary.com/simpleview/image/upload/v1634555140/clients/norway/Oslo_operahus_2_447c01a6-7d1c-4cd6-a87a-0c38e552a893.jpg']
    , ['Romania', 'Palace Of Parliament', "The Palace of the Parliament, also known as the Republic's House or People's House/People's Palace, is the seat of the Parliament of Romania, located atop Dealul Spirii in Bucharest, the national capital.", 'https://en.wikipedia.org/wiki/Palace_of_the_Parliament', 'https://lp-cms-production.imgix.net/2019-06/8d16291e7117291393a7c3194bf3b2d5-palace-of-parliament.jpg']
    , ['Palau', 'Palau', 'Palau is an archipelago of over 500 islands, part of the Micronesia region in the western Pacific Ocean. Koror Island is home to the former capital, also named Koror, and is the islands’ commercial center. The larger Babeldaob has the present capital, Ngerulmud, plus mountains and sandy beaches on its east coast. In its north, ancient basalt monoliths known as Badrulchau lie in grassy fields surrounded by palm trees.', 'google.com', 'https://www.state.gov/wp-content/uploads/2019/04/Palau-2117x1406.jpg']
    , ['United Arab Emirates', 'Palm Jumeirah island', 'The tree-shaped Palm Jumeirah island is known for glitzy hotels, posh apartment towers and upmarket global restaurants. Food trucks offering snacks like shawarma dot the Palm Jumeirah Boardwalk, popular for its views of the Dubai coastline and the sail-shaped Burj Al Arab hotel. Beach clubs with spas and infinity pools turn into boisterous nightclubs with live DJs in the evening.', 'google.com', 'https://www.tripsavvy.com/thmb/tjpE0m9-2PQhJ-oEUESvOg79lgA=/3560x2670/smart/filters:no_upscale()/aerial-view-of-dubai-palm-jumeirah-island--united-arab-emirates-1097789900-b6c44835cb3945f481427a612f2cdd0b.jpg']
    , ['Panama', 'Panama Canal', 'The Panama Canal is an artificial 82 km waterway in Panama that connects the Atlantic Ocean with the Pacific Ocean and divides North and South America. The canal cuts across the Isthmus of Panama and is a conduit for maritime trade.', 'https://en.wikipedia.org/wiki/Panama_Canal', 'https://cdn.britannica.com/73/75873-050-D9FF99F9/tugboat-one-ship-locks-Panama-Canal.jpg']
    , ['Italy', 'Pantheon', 'The Pantheon is a former Roman temple and, since 609 AD, a Catholic church in Rome, Italy, on the site of an earlier temple commissioned by Marcus Agrippa during the reign of Augustus. It was rebuilt by the emperor Hadrian and probably dedicated c. 126 AD.', 'https://en.wikipedia.org/wiki/Pantheon,_Rome', 'https://monolithicdome.com/vault/img/2021/07/20/60f708d73c0d975e795f679e/rome-italy-pantheon-exterior-complete-marino.huge.jpg']
    , ['Oceania', 'Papua New Guinea', 'Papua New Guinea, in the southwestern Pacific, encompasses the eastern half of New Guinea and its offshore islands. A country of immense cultural and biological diversity, it’s known for its beaches and coral reefs. Inland are active volcanoes, granite Mt. Wilhelm, dense rainforest and hiking routes like the Kokoda Trail. There are also traditional tribal villages, many with their own languages.', 'google.com', 'https://www.journeyera.com/wp-content/uploads/2019/11/MADANG-PAPUA-NEW-GUINEA-0229-1.jpg.webp']
    , ['Spain', 'Parc Guell', 'Parc Güell is a privatized park system composed of gardens and architectural elements located on Carmel Hill, in Barcelona, Catalonia, Spain. Carmel Hill belongs to the mountain range of Collserola – the Parc del Carmel is located on the northern face.', 'https://en.wikipedia.org/wiki/Park_Güell', 'https://cdn.getyourguide.com/img/location/53bffbaac9423-m1398847398.jpg/99.jpg']
    , ['Mexico', 'Paricutin Volcano', 'Parícutin is a cinder cone volcano located in the Mexican state of Michoacán, near the city of Uruapan and about 322 kilometers west of Mexico City. The volcano surged suddenly from the cornfield of local farmer Dionisio Pulido in 1943, attracting both popular and scientific attention.', 'https://en.wikipedia.org/wiki/Parícutin', 'https://cdn.britannica.com/58/175958-050-F61E842E/Paricutin-Mexico.jpg']
    ];
const twoHundreds = [
    ['Mexico', 'Paricutin Volcano', 'Parícutin is a cinder cone volcano located in the Mexican state of Michoacán, near the city of Uruapan and about 322 kilometers west of Mexico City. The volcano surged suddenly from the cornfield of local farmer Dionisio Pulido in 1943, attracting both popular and scientific attention.', 'https://en.wikipedia.org/wiki/Parícutin', 'https://cdn.britannica.com/58/175958-050-F61E842E/Paricutin-Mexico.jpg']
    , ['Argentina', 'Patagonia', 'Patagonia is a region encompassing the vast southernmost tip of South America, shared by Argentina and Chile, with the Andes Mountains as its dividing line. The Argentine side features arid steppes, grasslands and deserts, while the Chilean has glacial fjords and temperate rainforest. Argentina’s famed RN-40 highway passes the pinnacles of Monte Fitz Roy and Perito Moreno Glacier in Los Glaciares National Park.', 'https://en.wikipedia.org/wiki/Patagonia', 'https://cdn.theculturetrip.com/wp-content/uploads/2017/07/patagonia-quiquefepe-flickr-1024x683.jpg']
    , ['United States', 'Pearl Harbor', 'The attack on Pearl Harbor was a surprise military strike by the Imperial Japanese Navy Air Service upon the United States against the naval base at Pearl Harbor in Honolulu, Territory of Hawaii, just before 8:00 a.m., on Sunday, December 7, 1941.', 'https://en.wikipedia.org/wiki/Attack_on_Pearl_Harbor', 'https://www.gohawaii.com/sites/default/files/styles/image_gallery_bg_xl/public/hero-unit-images/Pearl%20Harbor%20Memorial%20Aerial.jpg?itok=8JLZt1wY']
    , ['United States', 'Pentagon', 'The Pentagon is the headquarters building of the United States Department of Defense. It was constructed on an accelerated schedule during World War II. As a symbol of the U.S. military, the phrase The Pentagon is often used as a metonym for the Department of Defense and its leadership.', 'https://en.wikipedia.org/wiki/The_Pentagon', 'https://cdn.britannica.com/85/94185-050-B3B95F6F/view-Pentagon-Arlington-Va.jpg']
    , ['Iran', 'Persepolis', 'Persepolis was the ceremonial capital of the Achaemenid Empire. It is situated in the plains of Marvdasht, encircled by southern Zagros mountains of the Iranian plateau. Modern day Shiraz is situated 60 kilometres southwest of the ruins of Persepolis. The earliest remains of Persepolis date back to 515 BC.', 'https://en.wikipedia.org/wiki/Persepolis', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Gate_of_All_Nations%2C_Persepolis.jpg']
    , ['Jordan', 'Petra', 'Petra is a famous archaeological site in Jordan\'s southwestern desert. Dating to around 300 B.C., it was the capital of the Nabatean Kingdom. Accessed via a narrow canyon called Al Siq, it contains tombs and temples carved into pink sandstone cliffs, earning its nickname, the "Rose City." Perhaps its most famous structure is 45m-high Al Khazneh, a temple with an ornate, Greek-style facade, and known as The Treasury.', 'https://en.wikipedia.org/wiki/Petra_(band)', 'https://cdn.britannica.com/88/189788-050-9B5DB3A4/Al-Dayr-Petra-Jordan.jpg']
    , ['Malaysia', 'Petronas Towers', 'The Petronas Towers, also known as the Petronas Twin Towers or KLCC Twin Towers, are 88-storey supertall skyscrapers in Kuala Lumpur, Malaysia. At 451.9 metres. From 1998 and 2004, they were officially classified as the tallest buildings in the world until it was defeated by the 2005 completion of the Taipei 101.', 'https://en.wikipedia.org/wiki/Petronas_Towers', 'https://www.thorntontomasetti.com/sites/default/files/styles/paragraph_slideshow/public/klcc_4.jpg?itok=8Z9MMFz6']
    , ['Thailand', 'Phuket', 'Phuket, a rainforested, mountainous island in the Andaman Sea, has some of Thailand’s most popular beaches, mainly situated along the clear waters of the western shore. The island is home to many high-end seaside resorts, spas and restaurants. Phuket City, the capital, has old shophouses and busy markets. Patong, the main resort town, has many nightclubs, bars and discos.', 'https://en.wikipedia.org/wiki/Phuket_province', 'https://www.planetware.com/photos-large/THA/phuket-island.jpg']
    , ['London', 'Piccadilly Circus', 'Piccadilly Circus is a road junction and public space of London\'s West End in the City of Westminster. It was built in 1819 to connect Regent Street with Piccadilly. In this context, a circus, from the Latin word meaning "circle", is a round open space at a street junction.', 'https://en.wikipedia.org/wiki/Piccadilly_Circus', 'https://cdn.britannica.com/39/99939-050-BE719726/Piccadilly-Circus-London.jpg']
    , ['Chile', 'Plaza de Armas', 'The Plaza de Armas De San Fernando is the main square of Santiago, the capital of Chile. Plaza de Armas metro station is located under the square.', 'https://en.wikipedia.org/wiki/Plaza_de_Armas_(Santiago)', 'https://image.arrivalguides.com/x/09/1dd4f12c93341d6262eaf77ac8887c60.jpg']
    , ['Peru', 'Lima Main Square', "The Plaza Mayor de Lima, or Plaza de Armas de Lima, is the birthplace of the city of Lima, as well as the core of the city. Located in the Historic Centre of Lima, it is surrounded by the Government Palace, Lima Metropolitan Cathedral, Archbishop's Palace of Lima, the Municipal Palace, and the Palacio de la Unión.", 'https://en.wikipedia.org/wiki/Plaza_Mayor_de_Lima', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/6a/a0/24/20180322-145842-largejpg.jpg?w=1200&h=1200&s=1']
    , ['Italy', 'Pompeii', 'Pompeii is a vast archaeological site in southern Italy’s Campania region, near the coast of the Bay of Naples. Once a thriving and sophisticated Roman city, Pompeii was buried under meters of ash and pumice after the catastrophic eruption of Mount Vesuvius in 79 A.D. The preserved site features excavated ruins of streets and houses that visitors can freely explore.', 'https://en.wikipedia.org/wiki/Pompeii', 'https://cdn.britannica.com/52/159952-050-00D2DCB3/roadway-Pompeii-Italy.jpg']
    , ['China', 'Potala Palace', 'The Potala Palace is a dzong fortress in Lhasa, Tibet. It was the winter palace of the Dalai Lamas from 1649 to 1959, has been a museum since then, and has been a World Heritage Site since 1994. The palace is named after Mount Potalaka, the mythical abode of the bodhisattva Avalokiteśvara.', 'https://en.wikipedia.org/wiki/Potala_Palace', 'https://whc.unesco.org/uploads/thumbs/site_0707_0001-1200-630-20110920202629.jpg']
    , ['Czech Republic', 'Prague Castle', 'Prague Castle is a castle complex in Prague, Czech Republic, built in the 9th century. It is the official office of the President of the Czech Republic. The castle was a seat of power for kings of Bohemia, Holy Roman emperors, and presidents of Czechoslovakia.', 'https://en.wikipedia.org/wiki/Prague_Castle', 'https://www.tripsavvy.com/thmb/0g_ZQkg0_VyM5HtQQLff4kp8v28=/2700x1800/filters:fill(auto,1)/DSCF3648-f18cc25d2d5143988d2b0ac8f9d84714.jpg']
    , ['Saudi Arabia', "Prophet's Mosque", "Al-Masjid an-Nabawi, known in English as the Prophet's Mosque, is a mosque built by the Islamic prophet Muhammad in the city of Medina in the Al Madinah Province of Saudi Arabia.", 'https://en.wikipedia.org/wiki/Al-Masjid_an-Nabawi', 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Masjid_Nabawi_The_Prophet%27s_Mosque%2C_Madina.jpg']
    , ['Kazakhstan', 'Karaotkel Bridge', 'The Ramstor Bridge is an Arch bridge spanning the Ishim River in Nur-Sultan, Kazakhstan. It was built between 2007 and 2008 as a road bridge crossing the Ishim River.', 'https://en.wikipedia.org/wiki/Ramstor_Bridge', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Astana%2C_by_the_River_%284054863149%29.jpg/1200px-Astana%2C_by_the_River_%284054863149%29.jpg']
    , ['India', 'Red Fort', 'The Red Fort or Lal Qila is a historic fort in Old Delhi, Delhi in India that served as the main residence of the Mughal Emperors. Emperor Shah Jahan commissioned construction of the Red Fort on 12 May 1638, when he decided to shift his capital from Agra to Delhi.', 'https://en.wikipedia.org/wiki/Red_Fort', 'https://cdn.britannica.com/20/189820-050-D650A54D/Red-Fort-Old-Delhi-India.jpg']
    , ['Germany', 'Rhine River', 'The Rhine is one of the major European rivers. The river begins in the Swiss canton of Graubünden in the southeastern Swiss Alps. It forms part of the Swiss-Liechtenstein, Swiss-Austrian, Swiss-German borders.', 'https://en.wikipedia.org/wiki/Rhine', 'https://www.tauck.com/-/media/Tauck/Editorial/Images/SEO-Pages/River-Cruise-Guides/River-Facts/RiverFacts_Rhine_hero.jpg?rev=16685013712b454689ac4e4293378f97']
    , ['Italy', 'Rialto Bridge', 'The Rialto Bridge is the oldest of the four bridges spanning the Grand Canal in Venice, Italy. Connecting the sestieri of San Marco and San Polo, it has been rebuilt several times since its first construction as a pontoon bridge in 1173, and is now a significant tourist attraction in the city.', 'https://en.wikipedia.org/wiki/Rialto_Bridge', 'https://cdn.britannica.com/64/153464-050-551A86F7/Rialto-Bridge-Grand-Canal-Venice.jpg']
    , ['Netherlands', 'Rijksmuseum', 'The Rijksmuseum is the national museum of the Netherlands dedicated to Dutch arts and history and is located in Amsterdam. The museum is located at the Museum Square in the borough of Amsterdam South, close to the Van Gogh Museum, the Stedelijk Museum Amsterdam, and the Concertgebouw.', 'https://en.wikipedia.org/wiki/Rijksmuseum', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Rijksmuseum_in_Amsterdam.jpg']
    , ['United Kingdom', 'Rock of Gibraltar', 'The Rock of Gibraltar is a monolithic limestone promontory located in the British territory of Gibraltar, near the southwestern tip of Europe on the Iberian Peninsula, and near the entrance to the Mediterranean. It is 426 m high.', 'https://en.wikipedia.org/wiki/Rock_of_Gibraltar', 'https://www.worldatlas.com/r/w1200/upload/32/32/be/shutterstock-449229811.jpg']
    , ['United States', 'Rodeo Drive', 'Rodeo Drive is a two-mile-long street in Beverly Hills, California, with its southern segment in the City of Los Angeles. Its southern terminus is at Beverwil Drive, and its northern terminus is at its intersection with Sunset Boulevard in Beverly Hills.', 'https://en.wikipedia.org/wiki/Rodeo_Drive', 'https://upload.wikimedia.org/wikipedia/commons/1/12/Rodeo_Drive%2C_Beverly_Hills%2C_LA%2C_CA%2C_jjron_21.03.2012.jpg']
    , ['New Zealand', 'Rotorua', "Rotorua, a town set on its namesake lake on New Zealand's North Island, is renowned for its geothermal activity and Maori culture. In Te Puia’s Whakarewarewa Valley, there are bubbling mud pools and the 30m-tall Pohutu Geyser, which erupts many times daily. It’s also home to a living Maori village and the New Zealand Maori Arts and Crafts Institute, with traditional wood carving and weaving schools.", 'https://en.wikipedia.org/wiki/Rotorua', 'https://cdn.audleytravel.com/2188/1559/79/1022064-champagne-pool-rotorua.jpg']
    , ['United States', 'Route 66', 'U.S. Route 66 or U.S. Highway 66 was one of the original highways in the United States Numbered Highway System. US 66 was established on November 11, 1926, with road signs erected the following year.', 'https://en.wikipedia.org/wiki/U.S._Route_66', 'https://www.travelandleisure.com/thmb/kRk7YwSN7BsE61TenPE80rEIcQU=/2000x1287/filters:fill(auto,1)/GettyImages-154788629-2000-4e8f5a4011604916b200a258290b03b8.jpg']
    , ['North Korea', 'Ryugyong Hotel', 'The Ryugyong Hotel, or Yu-Kyung Hotel, more commonly known outside of North Korea as the "Hotel of Doom", is an unfinished 105-story, 330-metre-tall pyramid-shaped skyscraper in Pyongyang, North Korea. Its name is also one of the historical names for Pyongyang.', 'https://en.wikipedia.org/wiki/Ryugyong_Hotel', 'https://www.uritours.com/wp-content/uploads/2020/05/ryugyong-hotel-traffic-officer-pyongyang.jpg']
    , ['Spain', 'La Sagrada Familia', 'The Basílica i Temple Expiatori de la Sagrada Família, is a church in the Eixample district of Barcelona, Catalonia, Spain, and is currently the largest unfinished Roman Catholic church. Designed by the Catalan architect Antoni Gaudí, his work on Sagrada Família is part of a UNESCO World Heritage Site.', 'https://en.wikipedia.org/wiki/Sagrada_Família', 'https://lp-cms-production.imgix.net/2019-06/8ae1c56041e64517e29372a889f1beb7-la-sagrada-familia.jpg']
    , ['Morocco', 'Sahara Desert', 'The Sahara is a desert on the African continent. With an area of 9,200,000 square kilometres, it is the largest hot desert in the world and the third-largest desert overall, smaller only than the deserts of Antarctica and the northern Arctic.', 'https://en.wikipedia.org/wiki/Sahara', 'https://cdn.britannica.com/10/152310-050-5A09D74A/Sand-dunes-Sahara-Morocco-Merzouga.jpg']
    , ['Bolivia', 'Uyuni Salt Flat', 'Salar de Uyuni, amid the Andes in southwest Bolivia, is the world’s largest salt flat. It’s the legacy of a prehistoric lake that went dry, leaving behind a desertlike, nearly 11,000-sq.-km. landscape of bright-white salt, rock formations and cacti-studded islands. Its otherworldly expanse can be observed from central Incahuasi Island. Though wildlife is rare in this unique ecosystem, it harbors many pink flamingos.', 'https://es.wikipedia.org/wiki/Salar_de_Uyuni', 'https://i.natgeofe.com/n/857a969e-9fe6-4b5e-959f-157ad9fdf7f9/reflection-salar-de-uyuni-bolivia_4x3.jpg']
    , ['Guatemala', 'Santa Catalina Arch', 'The Santa Catalina Arch is one of the distinguishable landmarks in Antigua Guatemala, Guatemala, located on 5th Avenue North. Built in the 17th century, it originally connected the Santa Catalina convent to a school, allowing the cloistered nuns to pass from one building to the other without going out on the street.', 'https://en.wikipedia.org/wiki/Arco_de_Santa_Catalina', 'https://img.theculturetrip.com/wp-content/uploads/2017/08/1200px-gt056-antigua_archhorz.jpg']
    , ['Brazil', 'São Paulo', "São Paulo, Brazil’s vibrant financial center, is among the world's most populous cities, with numerous cultural institutions and a rich architectural tradition. Its iconic buildings range from its neo-Gothic cathedral and the 1929 Martinelli skyscraper to modernist architect Oscar Niemeyer’s curvy Edifício Copan. The colonial-style Pátio do Colégio church marks where Jesuit priests founded the city in 1554.", 'https://en.wikipedia.org/wiki/São_Paulo', 'https://lp-cms-production.imgix.net/image_browser/shutterstockRF_153080222.jpg']
    , ['Austria', 'Schönbrunn Palace', 'Schönbrunn Palace was the main summer residence of the Habsburg rulers, located in Hietzing, Vienna. The name Schönbrunn has its roots in an artesian well from which water was consumed by the court.', 'https://en.wikipedia.org/wiki/Schönbrunn_Palace', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Wien_-_Schloss_Sch%C3%B6nbrunn.JPG/1200px-Wien_-_Schloss_Sch%C3%B6nbrunn.JPG']
    , ['Tanzania', 'Serengeti', 'The Serengeti ecosystem is a geographical region in Africa, spanning northern Tanzania. The protected area within the region includes approximately 30,000 km² of land, including the Serengeti National Park and several game reserves.', 'https://en.wikipedia.org/wiki/Serengeti', 'https://www.google.com/search?q=Serengeti+National+Park&client=opera-gx&hs=lCo&sxsrf=ALiCzsYKcL9e9_l_Sa2zRd3Hgpl1CgbYtA:1664660239358&source=lnms&tbm=isch&sa=X&ved=2ahUKEwirhPTR_r_6AhVyPH0KHYHYA84Q_AUoAXoECAIQAw&biw=1399&bih=700&dpr=2#imgrc=XjKHKXiQgRUhnM']
    , ['Seychelles', 'Seychelles', "The Seychelles is an archipelago of 115 islands in the Indian Ocean, off East Africa. It's home to numerous beaches, coral reefs and nature reserves, as well as rare animals such as giant Aldabra tortoises. Mahé, a hub for visiting the other islands, is home to capital Victoria. It also has the mountain rainforests of Morne Seychellois National Park and beaches, including Beau Vallon and Anse Takamaka.", 'https://en.wikipedia.org/wiki/Seychelles', 'https://cdn.britannica.com/76/194376-050-925CA23D/Clock-tower-Victoria-Seychelles.jpg']
    , ['Uzbekistan', 'Shah-i-Zinda', 'Shah-i-Zinda is a necropolis in the north-eastern part of Samarkand, Uzbekistan.', 'https://en.wikipedia.org/wiki/Shah-i-Zinda', 'https://www.abouther.com/sites/default/files/2018/09/13/shahizinda_2.jpg']
    , ['United Arab Emirates', 'Sheikh Zayed Grand Mosque', 'The Sheikh Zayed Grand Mosque is located in Abu Dhabi, the capital city of the United Arab Emirates. The largest mosque in the country, it is the key place of worship for daily prayers.', 'https://en.wikipedia.org/wiki/Sheikh_Zayed_Grand_Mosque', 'http://cdn.cnn.com/cnnnext/dam/assets/181122125456-sheikh-zayed-grand-mosque-stock.jpg']
    , ['Myanmar', 'Shwedagon Pagoda', 'The Shwedagon Pagoda; Mon: ကျာ်ဒဂုၚ်; officially named Shwedagon Zedi Daw and also known as the Great Dagon Pagoda and the Golden Pagoda is a gilded stupa located in Yangon, Myanmar.', 'https://en.wikipedia.org/wiki/Shwedagon_Pagoda', 'https://cdn.theculturetrip.com/wp-content/uploads/2017/12/sunset-at-the-shwedagon-pagoda.jpg']
    , ['Russia', 'Siberia', 'Siberia is a vast Russian province encompassing most of Northern Asia, with terrain spanning tundra, coniferous forest and mountain ranges including the Ural, Altai and Verkhoyansk. Lake Baikal, in its south, is the world’s deepest lake, circled by a network of hiking paths called the Great Baikal Trail. The Trans-Siberian Railway passes Baikal on its route between Moscow and the Sea of Japan.', 'https://en.wikipedia.org/wiki/Siberia', 'https://www.worldatlas.com/upload/ee/e4/10/shutterstock-1839034999.jpg']
    , ['Sri Lanka', 'Sigiriya', 'Sigiriya or Sinhagiri is an ancient rock fortress located in the northern Matale District near the town of Dambulla in the Central Province, Sri Lanka. It is a site of historical and archaeological significance that is dominated by a massive column of rock approximately 180 m high.', 'https://en.wikipedia.org/wiki/Sigiriya', 'https://lh5.googleusercontent.com/13TyIlvhQD5nFy_fHX_HXWbQ7DrnQyZhtZCHc4aZLk2oaQqEoJNt7TYShwzK0-HGdYaVqIf_tXY2yIEPeGdEFpPP9tTwErhUnOciLgQzmV5wXOB69AaxbWmdCU4J4k2lOSbyQ6u1']
    , ['China', 'Silk Road', 'The Silk Road was a network of Eurasian trade routes active from the second century BCE until the mid-15th century. Spanning over 6,400 kilometers, it played a central role in facilitating economic, cultural, political, and religious interactions between the East and West.', 'https://en.wikipedia.org/wiki/Silk_Road', 'https://www.thoughtco.com/thmb/RcvaZ_9jusEryPJR77HzW0It6jI=/3865x2576/filters:fill(auto,1)/desert-traveller-171605010-5b63d07dc9e77c002cba836a.jpg']
    , ['Singapore', 'Singapore', 'Singapore, officially the Republic of Singapore, is a sovereign island country and city-state in maritime Southeast Asia.', 'https://en.wikipedia.org/wiki/Singapore', 'https://i.natgeofe.com/n/d3eb75f2-1cfb-4934-8def-8ff7a39985b8/1-urban-innovator-singapore-AP_17028110123351_3x2.jpg']
    , ['Portugal', 'Sintra', 'Sintra (Santa Maria e São Miguel, São Martinho e São Pedro de Penaferrim) is a civil parish in the municipality of Sintra, Lisbon District, Portugal. It was formed in 2013 by the merger of the former parishes Santa Maria e São Miguel, São Martinho and São Pedro de Penaferrim.', 'https://en.wikipedia.org/wiki/Sintra_(Santa_Maria_e_São_Miguel,_São_Martinho_e_São_Pedro_de_Penaferrim)', 'https://www.roadaffair.com/wp-content/uploads/2018/09/pena-palace-sintra-portugal-shutterstock_519387292.jpg']
    , ['Vatican City', 'Sistine Chapel', 'The Sistine Chapel is a chapel in the Apostolic Palace, in Vatican City and the official residence of the pope. Originally known as the Cappella Magna, the chapel takes its name from Pope Sixtus IV, who had it built between 1473 and 1481.', 'https://en.wikipedia.org/wiki/Sistine_Chapel', 'https://www.thoughtco.com/thmb/f6CwTLpePy7Pxkvn6e0y0PKSqH0=/3456x2592/smart/filters:no_upscale()/SistineChapel-57ffd66e5f9b5805c2ac4916.jpg']
    , ['New Zealand', 'Sky Tower', "The Sky Tower (Māori: Pourewa Rangi) is a telecommunications and observation tower in Auckland, New Zealand. Located at the corner of Victoria and Federal Streets within the city's CBD, it is 328 metres (1,076 ft) tall, as measured from ground level to the top of the mast, making it the tallest freestanding structure in the Southern Hemisphere", 'https://en.wikipedia.org/wiki/Sky_Tower_(Auckland)', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/dc/e6/a1/enjoy-beautiful-views.jpg?w=1200&h=-1&s=1']
    , ['Antarctic', 'South Pole', "The South Pole, also known as the Geographic South Pole, Terrestrial South Pole or 90th Parallel South, is one of the two points where Earth's axis of rotation intersects its surface.", 'https://en.wikipedia.org/wiki/South_Pole', 'https://storage.googleapis.com/oceanwide_web/media-dynamic/cache/widen_1600_progressive/media/default/0001/19/5e34aa0c80324eefbfb75103936a49cc4697794f.jpeg']
    , ['United States', 'Space Needle', 'Iconic, 605-ft.-tall spire at the Seattle Center, with an observation deck & a rotating restaurant.', 'https://en.wikipedia.org/wiki/Space_Needle', 'https://www.tripsavvy.com/thmb/krkzDOJHQD0sTAmeTT3dsiD5Xfw=/1825x1369/smart/filters:no_upscale()/GettyImages-610712690-5c3ba9c646e0fb00018dead8.jpg']
    , ['Italy', 'Spanish Steps', 'The Spanish Steps in Rome, Italy, climb a steep slope between the Piazza di Spagna at the base and Piazza Trinità dei Monti, dominated by the Trinità dei Monti church, at the top.', 'https://en.wikipedia.org/wiki/Spanish_Steps', 'https://help-tourists-in-rome.com/wp-content/uploads/2019/08/ROM_Spanische-Treppe_l-2-scaled.jpg']
    , ['Russia', "St. Basil's Cathedral", "The Cathedral of Vasily the Blessed, commonly known as Saint Basil's Cathedral, is an Orthodox church in Red Square of Moscow, and is one of the most popular cultural symbols of Russia.", 'https://en.wikipedia.org/wiki/Saint_Basil%27s_Cathedral', 'https://gallerybyzantium.com/wp-content/uploads/2019/01/st-basil-cathedral_1.jpg']
    , ['Saint Lucia', 'Saint Lucia', 'Saint Lucia is an Eastern Caribbean island nation with a pair of dramatically tapered mountains, the Pitons, on its west coast. Its coast is home to volcanic beaches, reef-diving sites, luxury resorts and fishing villages. Trails in the interior rainforest lead to waterfalls like the 15m-high Toraille, which pours over a cliff into a garden. The capital, Castries, is a popular cruise port.', 'https://en.wikipedia.org/wiki/Saint_Lucia', 'https://www.stlucia.org/wp-content/uploads/2019/04/sms-preview.jpg']
    , ['Vatican City', "St. Peter's Basilica", "The Papal Basilica of Saint Peter in the Vatican, or simply Saint Peter's Basilica, is a church built in the Renaissance style located in Vatican City, the papal enclave that is within the city of Rome, Italy.", 'https://en.wikipedia.org/wiki/St._Peter%27s_Basilica', 'https://images.prismic.io/mystique/659698ea-b932-4e1e-98cb-9e5be5c8ddb8_st+peter%27s+basilica+9.jpg?auto=compress,format']
    , ['Austria', "St. Stephen's Cathedral", "St. Stephen's Cathedral is the mother church of the Roman Catholic Archdiocese of Vienna and the seat of the Archbishop of Vienna, Christoph Cardinal Schönborn, OP.", 'https://en.wikipedia.org/wiki/St._Stephen%27s_Cathedral,_Vienna', 'https://govisity.com/wp-content/uploads/2019/02/St.-Stephen%E2%80%99s-Cathedral-Best-Places-to-Visit-in-Vienna.jpg']
    , ['Italy', 'Gallery of the Academy of Florence', 'The Galleria dell\'Accademia di Firenze, or "Gallery of the Academy of Florence", is an art museum in Florence, Italy. It is best known as the home of Michelangelo\'s sculpture David. It also has other sculptures by Michelangelo and a large collection of paintings by Florentine artists, mostly from the period 1300–1600.', 'https://en.wikipedia.org/wiki/Galleria_dell%27Accademia', 'https://upload.wikimedia.org/wikipedia/commons/3/37/David_by_Michelangelo_in_The_Gallery_of_the_Accademia_di_Belle_Arti.jpg']
    , ['United States', 'Statue of Liberty', 'The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor in New York City, in the United States.', 'https://en.wikipedia.org/wiki/Statue_of_Liberty', 'https://www.history.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTY1MTc1MTk3ODI0MDAxNjA5/topic-statue-of-liberty-gettyimages-960610006-promo.jpg']
    , ['India', 'Statue Of Unity', "The Statue of Unity is the world's tallest statue, with a height of 182 metres, located in the state of Gujarat, India. It depicts Indian statesman and independence activist Vallabhbhai Patel, who was the first deputy prime minister and home minister of independent India and an adherent of Mahatma Gandhi.", 'https://en.wikipedia.org/wiki/Statue_of_Unity', 'https://mybestplace.com/uploads/2019/04/Statue-of-Unity-India-2.jpg']
    , ['United Kingdom', 'Stonehenge', 'Stonehenge is a prehistoric monument on Salisbury Plain in Wiltshire, England, two miles west of Amesbury. It consists of an outer ring of vertical sarsen standing stones, each around 13 feet high, seven feet wide, and weighing around 25 tons, topped by connecting horizontal lintel stones.', 'https://en.wikipedia.org/wiki/Stonehenge', 'https://upload.wikimedia.org/wikipedia/commons/3/3c/Stonehenge2007_07_30.jpg']
    , ['Egypt', 'Suez Canal', 'The Suez Canal is an artificial sea-level waterway in Egypt, connecting the Mediterranean Sea to the Red Sea through the Isthmus of Suez and dividing Africa and Asia. The canal is a route of trade between Europe and Asia.', 'https://en.wikipedia.org/wiki/Suez_Canal', 'https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iz4jFfdXx7uk/v0/1200x-1.jpg']
    , ['Brunei', 'Omar Ali Saifuddien Mosque', "Omar Ali Saifuddien Mosque is a mosque in Bandar Seri Begawan, the capital of Brunei. It is one of the country's two masjid negara or national mosques, as well as a national landmark.", 'https://en.wikipedia.org/wiki/Omar_Ali_Saifuddien_Mosque', 'https://www.idesignarch.com/wp-content/uploads/Sultan-Omar-Ali-Saifuddin-Mosque_1.jpg']
    , ['Switzerland', 'Swiss Alps', 'The Alpine region of Switzerland, conventionally referred to as the Swiss Alps, represents a major natural feature of the country and is, along with the Swiss Plateau and the Swiss portion of the Jura Mountains, one of its three main physiographic regions.', 'https://en.wikipedia.org/wiki/Swiss_Alps', 'https://deih43ym53wif.cloudfront.net/zermatt-matterhorn-switzerland-shutterstock_1298208013_44fea015e5.jpeg']
    , ['Australia', 'Sydney Harbour Bridge', 'The Sydney Harbour Bridge is a steel through arch bridge in Sydney, spanning Sydney Harbour from the central business district (CBD) to the North Shore.', 'https://en.wikipedia.org/wiki/Sydney_Harbour_Bridge', 'https://www.wanderlustchloe.com/wp-content/uploads/2021/07/Sydney-Harbour-Bridge-11.jpg']
    , ['Australia', 'Sydney Opera House', "The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the foreshore of Sydney Harbour, it is widely regarded as one of the world's most famous and distinctive buildings and a masterpiece of 20th century architecture.", 'https://en.wikipedia.org/wiki/Sydney_Opera_House', 'https://cdn.britannica.com/85/95085-050-FBA5ABEE/Sydney-Opera-House-Bennelong-Point-Port-Jackson.jpg']
    , ['South Africa', "Maclear's Beacon", 'Table Mountain is a flat-topped mountain forming a prominent landmark overlooking the city of Cape Town in South Africa. It is a significant tourist attraction, with many visitors using the cableway or hiking to the top.', 'https://en.wikipedia.org/wiki/Table_Mountain', 'https://media.cntraveler.com/photos/5b742b191f8f5f5aacc37829/16:9/w_2560,c_limit/Table-Mountain_GettyImages-103891332.jpg']
    , ['Taiwan', 'Taipei 101', "Taipei 101, formerly known as the Taipei World Financial Center, is a skyscraper in Taipei, Taiwan. This building was officially classified as the world's tallest from its opening in 2004 until the 2009 completion of the Burj Khalifa in Dubai, UAE. Upon completion, it became the first skyscraper to exceed a height of half a kilometer.", 'https://en.wikipedia.org/wiki/Taipei_101', 'https://lp-cms-production.imgix.net/2019-06/f15f7b57ab31c217f471c6712a2654e0-taipei-101.jpg']
    , ['India', 'Taj Mahal', 'The Taj Mahal, is an Islamic ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1631 by the Mughal emperor Shah Jahan to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself.', 'https://en.wikipedia.org/wiki/Taj_Mahal', 'https://cdn.britannica.com/86/170586-050-AB7FEFAE/Taj-Mahal-Agra-India.jpg']
    , ['Estonia', 'Tallinn Town Hall', 'The Tallinn Town Hall is a building in the Vanalinn ("Old town") of Tallinn (Reval), Estonia, next to the Town Hall Square. The building is located in the south side of the medieval market square and is 36.8 metres (121 ft) long. The west wall is 14.5 metres (48 ft) in length, and the east is 15.2 metres (50 ft). It is a two-storey building with a spacious basement. It is the oldest town hall in the whole Baltic Sea region and Scandinavia.', 'https://en.wikipedia.org/wiki/Tallinn_Town_Hall', 'https://img.locationscout.net/images/2015-10/tallinn-town-hall-square-estonia_l.jpeg']
    , ['Kyrgyzstan', 'Tash Rabat', 'Tash Rabat is a well-preserved 15th-century stone caravanserai in At-Bashy District, Naryn Province, Kyrgyzstan, located at an altitude of 3,200 metres.', 'https://en.wikipedia.org/wiki/Tash_Rabat', 'https://img.itinari.com/pages/images/original/89309103-9361-481d-84f2-c6605e1fdc60-tash_rabat.jpg?ch=DPR&dpr=2.625&w=1600&s=4c3b4bab58384ac5a172040a8ad22568']
    , ['Australia', 'Tasmania', 'Tasmania is an island state of Australia. It is located 240 km to the south of the Australian mainland, separated from it by the Bass Strait. The archipelago contains the southernmost point of the Australian federation.', 'https://en.wikipedia.org/wiki/Tasmania', 'https://deih43ym53wif.cloudfront.net/wineglass-bay-freycinet-tasmania_shutterstock_630197330_58be12ee53.jpeg']
    , ['Greece', 'Temple of Apollo', 'The Temple of Apollo, god of music, harmony, light, healing, and oracles occupied the most important and prominent position in the Delphic Panhellenic Sanctuary.', 'https://en.wikipedia.org/wiki/Temple_of_Apollo_(Delphi)', 'https://www.tripsavvy.com/thmb/9CQDumX4gJGnCtUOlJlGDWnGqzM=/3639x2047/smart/filters:no_upscale()/temple-of-apollo--ca-330-bc--delphi--unesco-world-heritage-list--1987---greece--greek-civilization--4th-century-bc-588934555-5b55c4a646e0fb00376f95e5.jpg']
    , ['Indonesia', 'Besakih Great Temple', 'Besakih Temple is a pura complex in the village of Besakih on the slopes of Mount Agung in eastern Bali, Indonesia. It is the most important, the largest and holiest temple of Balinese Hinduism, and one of a series of Balinese temples.', 'https://en.wikipedia.org/wiki/Besakih_Temple', 'https://a.cdn-hotels.com/gdcs/production111/d1651/61dc3d9c-7058-40e5-84d1-951adad21f8f.jpg']
    , ['China', 'Temple of Heaven', 'The Temple of Heaven is an imperial complex of religious buildings situated in the southeastern part of central Beijing. The complex was visited by the Emperors of the Ming and Qing dynasties for annual ceremonies of prayer to Heaven for a good harvest.', 'https://en.wikipedia.org/wiki/Temple_of_Heaven', 'https://lp-cms-production.imgix.net/2019-06/7d17a3ca32132ece9d22b9b5553eb1ac-temple-of-heaven-park.jpg']
    , ['Mexico', 'San Juan Teotihuacán', 'Teotihuacan is a vast Mexican archaeological complex northeast of Mexico City. Running down the middle of the site, which was once a flourishing pre-Columbian city, is the Avenue of the Dead. It links the Temple of Quetzalcoatl, the Pyramid of the Moon and the Pyramid of the Sun, the latter two with panoramic views from their summits. Artifacts in the Museum of Teotihuacan Culture, on-site, include pottery and bones.', 'https://en.wikipedia.org/wiki/Teotihuacan', 'https://cdn.britannica.com/42/178942-050-5CF05C54/Pyramid-Moon-Teotihuacan-Mexico.jpg']
    , ['China', 'Three Gorges Dam', "The Three Gorges Dam is a hydroelectric gravity dam that spans the Yangtze River by the town of Sandouping, in Yiling District, Yichang, Hubei province, central China, downstream of the Three Gorges. The Three Gorges Dam has been the world's largest power station in terms of installed capacity since 2012.", 'https://en.wikipedia.org/wiki/Three_Gorges_Dam', 'https://d1e00ek4ebabms.cloudfront.net/production/38b20a2b-2443-4ee2-a09e-2ee1d3f82e48.jpg']
    , ['Bhutan', 'Paro Taktsang', "Paro Taktsang, is a sacred Vajrayana Himalayan Buddhist site located in the cliffside of the upper Paro valley in Bhutan. It is one of thirteen Tiger's Nest caves in historical Tibet in which Padmasambhava practiced and taught Vajrayana.", 'https://en.wikipedia.org/wiki/Paro_Taktsang', 'https://www.culturaobscura.com/wp-content/uploads/2019/05/IMG_2030-Version-2-copy-1200x750.jpg']
    , ['Guatemala', 'Tikal', 'Tikal is the ruin of an ancient city, which was likely to have been called Yax Mutal, found in a rainforest in Guatemala. It is one of the largest archeological sites and urban centers of the pre-Columbian Maya civilization. It is located in the archeological region of the Petén Basin in what is now northern Guatemala.', 'https://en.wikipedia.org/wiki/Tikal', 'https://travelingcanucks.com/wp-content/uploads/2018/08/tikal-38.jpg']
    , ['Mali', 'Timbuktu', 'Timbuktu is a city in Mali, situated twenty kilometres north of the Niger River. The town is the capital of the Tombouctou Region, one of the eight administrative regions of Mali. It had a population of 54,453 in the 2009 census.', 'https://en.wikipedia.org/wiki/Timbuktu', 'https://blackeconomics.co.uk/wp-content/uploads/2021/03/timbuktu.jpg']
    , ['Japan', 'Tokyo Tower', 'The Tokyo Tower is a communications and observation tower in the Shiba-koen district of Minato, Tokyo, Japan, built in 1958. At 332.9 meters, it is the second-tallest structure in Japan.', 'https://en.wikipedia.org/wiki/Tokyo_Tower', 'https://www.japanrailpassnow.com/wp-content/uploads/2016/09/Tokyo-Tower.jpg']
    , ['United Kingdom', 'Tower Bridge', 'Tower Bridge is a Grade I listed combined bascule and suspension bridge in London, built between 1886 and 1894, designed by Horace Jones and engineered by John Wolfe Barry with the help of Henry Marc Brunel.', 'https://en.wikipedia.org/wiki/Tower_Bridge', 'https://www.wanderlustchloe.com/wp-content/uploads/2022/02/Tower-Bridge-at-sunset.jpg']
    , ['United Kingdom', 'Tower of London', "The Tower of London, officially His Majesty's Royal Palace and Fortress of the Tower of London, is a historic castle on the north bank of the River Thames in central London.", 'https://en.wikipedia.org/wiki/Tower_of_London', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/c0/dc/f8/tower-of-london-white.jpg?w=1200&h=-1&s=1&cx=2515&cy=1577&chk=v1_1e1764bee68456e4ca27']
    , ['Netherlands', 'Keukenhof', "Keukenhof, also known as the Garden of Europe, is one of the world's largest flower gardens, situated in the municipality of Lisse, in the Netherlands. According to the official website, Keukenhof Park covers an area of 32 hectares (79 acres) and approximately 7 million flower bulbs are planted in the gardens annually. Keukenhof is widely known for its tulips, and it also features numerous other flowers, including hyacinths, daffodils, lilies, roses, carnations and irises.", 'https://en.wikipedia.org/wiki/Keukenhof', 'https://upload.wikimedia.org/wikipedia/commons/8/83/Tulip_fields_of_Holland.jpg']
    , ['Australia', 'Twelve Apostles', 'The Twelve Apostles is a collection of limestone stacks off the shore of Port Campbell National Park, by the Great Ocean Road in Victoria, Australia. Their proximity to one another has made the site a popular tourist attraction.', 'https://en.wikipedia.org/wiki/The_Twelve_Apostles_(Victoria)', 'https://upload.wikimedia.org/wikipedia/commons/e/e4/The_Twelve_Apostles_2011.jpg']
    , ['Italy', 'Uffizi Gallery', 'The Uffizi Gallery is a prominent art museum located adjacent to the Piazza della Signoria in the Historic Centre of Florence in the region of Tuscany, Italy.', 'https://en.wikipedia.org/wiki/Uffizi', 'https://www.througheternity.com/upload/CONF83/20180228/masterpieces_uffizi_gallery_florence-tSa-1200X630.jpg']
    , ['Australia', 'Uluru', 'Uluru, or Ayers Rock, is a massive sandstone monolith in the heart of the Northern Territory’s arid "Red Centre". The nearest large town is Alice Springs, 450km away. Uluru is sacred to indigenous Australians and is thought to have started forming around 550 million years ago. It’s within Uluru-Kata Tjuta National Park, which also includes the 36 red-rock domes of the Kata Tjuta (colloquially “The Olgas”) formation.', 'https://en.wikipedia.org/wiki/Uluru', 'https://image.cnbcfm.com/api/v1/image/106252448-1574138121546gettyimages-542566348.jpeg?v=1574138624']
    , ['Sweden', 'Vasa Museum', 'The Vasa Museum is a maritime museum in Stockholm, Sweden. Located on the island of Djurgården, the museum displays the only almost fully intact 17th-century ship that has ever been salvaged, the 64-gun warship Vasa that sank on her maiden voyage in 1628.', 'https://en.wikipedia.org/wiki/Vasa_Museum', 'http://www.nordicexperience.com/wp-content/uploads/2018/03/AdobeStock_61334100-1024x683.jpeg']
    , ['Vatican City', 'Vatican Museums', 'The Vatican Museums are the public museums of the Vatican City. They display works from the immense collection amassed by the Catholic Church and the papacy throughout the centuries, including several of the most renowned Roman sculptures and most important masterpieces of Renaissance art in the world.', 'https://en.wikipedia.org/wiki/Vatican_Museums', 'https://media.cntraveler.com/photos/5edeb3dad0ee55c69ea95b58/5:4/w_2500,h_2000,c_limit/VaticanMuseumInterior-BJPA09.jpg']
    , ['France', 'Palace of Versailles', 'The Palace of Versailles is a former royal residence built by King Louis XIV located in Versailles, about 12 miles west of Paris, France.', 'https://en.wikipedia.org/wiki/Palace_of_Versailles', 'https://i.natgeofe.com/n/75fbafd8-41d2-48ee-81d0-a200d04dd791/93247_16x9.jpg?w=1200']
    , ['Zambia', 'Victoria Falls', "Victoria Falls is a waterfall on the Zambezi River in southern Africa, which provides habitat for several unique species of plants and animals. It is located on the border between Zambia and Zimbabwe and is one of the world's largest waterfalls, with a width of 1,708 m.", 'https://en.wikipedia.org/wiki/Victoria_Falls', 'https://smartwatermagazine.com/sites/default/files/styles/thumbnail-1180x647/public/victoria_falls_1.jpg?itok=EgKN1vl3']
    , ['Jordan', 'Wadi Rum Reserve', 'Wadi Rum is a protected desert wilderness in southern Jordan. It features dramatic sandstone mountains like the many-domed Jebel Um Ishrin, and natural arches such as Burdah Rock Bridge. Many prehistoric inscriptions and carvings line rocky caverns and steep chasms, such as Khazali Canyon. The natural watering hole of Lawrence’s Spring is named after British soldier Lawrence of Arabia, who allegedly washed there.', 'https://en.wikipedia.org/wiki/Wadi_Rum', 'https://cdn.kimkim.com/files/a/content_articles/featured_photos/2887f35aa2f7cacc7772a5e433bf34f4638e90e2/big-ccf03cc343ababea46f4c4e94d23fdd6.jpg']
    , ['New Zealand', 'Waiheke Island', 'Waiheke Island is the second-largest island in the Hauraki Gulf of New Zealand. Its ferry terminal in Matiatia Bay at the western end is 21.5 km from the central-city terminal in Auckland. It is the most populated island in the gulf, with 9,790 permanent residents.', 'https://en.wikipedia.org/wiki/Waiheke_Island', 'https://i.insider.com/5e9e0bc7e61f3417c73f7bf7?width=1136&format=jpeg']
    , ['New Zealand', 'Waiotapu Thermal Wonderland', "Waiotapu is an active geothermal area at the southern end of the Okataina Volcanic Centre, just north of the Reporoa caldera, in New Zealand's Taupo Volcanic Zone. It is 27 kilometres south of Rotorua.", 'https://en.wikipedia.org/wiki/Waiotapu', 'https://upload.wikimedia.org/wikipedia/commons/a/ab/ChampagnePool-Wai-O-Tapu_rotated_MC.jpg']
    , ['Croatia', 'Walls of Dubrovnik', 'The Walls of Dubrovnik are a series of defensive stone walls surrounding the city of Dubrovnik in southern Croatia.', 'https://en.wikipedia.org/wiki/Walls_of_Dubrovnik', 'https://lp-cms-production.imgix.net/2021-06/shutterstockRF_662032261.jpg']
    , ['Belgium', 'Waterloo', 'Waterloo is a town south of Brussels, in Belgium. It’s known as the site of the final defeat of Emperor Napoleon I, in 1815. South of town, overlooking the battlefield, the Lion’s Mound is an artificial hill topped by a cast-iron lion. At its foot is a rotunda housing the Panorama of the Battle, a vast circular painting. Nearby, the Memorial 1815 is an underground center illustrating the battle’s historic importance.', 'https://en.wikipedia.org/wiki/Waterloo,_Belgium', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/0_Braine-l%27Alleud_051012_%281%29.JPG/1200px-0_Braine-l%27Alleud_051012_%281%29.JPG']
    , ['United Kingdom', 'Westminster Abbey', 'Westminster Abbey, formally titled the Collegiate Church of Saint Peter at Westminster, is a large, mainly Gothic abbey church in the City of Westminster, London, England, just to the west of the Palace of Westminster.', 'https://en.wikipedia.org/wiki/Westminster_Abbey', 'https://cdn.britannica.com/04/121204-050-61ECC30E/choir-Westminster-Abbey-London.jpg']
    , ['Canada', 'Whistler', "Whistler is a town north of Vancouver, British Columbia, that's home to Whistler Blackcomb, one of the largest ski resorts in North America. Besides skiing and snowboarding, the area offers snowshoeing, tobogganing and ski jumping at the Olympic Park, a venue for the 2010 Vancouver Winter Olympics. The hub of Whistler is a compact, chalet-style pedestrian village at the base of Whistler and Blackcomb mountains.", 'https://en.wikipedia.org/wiki/Whistler,_British_Columbia', 'https://cdn.whistler.com/s3/images/og/whistler-village-bc.jpg']
    , ['United Kingdom', 'White Cliffs of Dover', 'The White Cliffs of Dover is the region of English coastline facing the Strait of Dover and France. The cliff face, which reaches a height of 350 feet, owes its striking appearance to its composition of chalk accented by streaks of black flint, deposited during the Late Cretaceous.', 'https://en.wikipedia.org/wiki/White_Cliffs_of_Dover', 'https://cdn.audleytravel.com/2794/1995/79/1346733-white-cliffs-of-dover.jpg']
    , ['United States', 'White House', 'The White House is the official residence and workplace of the president of the United States. It is located at 1600 Pennsylvania Avenue NW in Washington, D.C., and has been the residence of every U.S. president since John Adams in 1800.', 'https://en.wikipedia.org/wiki/White_House', 'https://www.nps.gov/common/uploads/cropped_image/primary/F0CEDDA8-CDA3-A365-792FF3B0EB0FCFF8.jpg?width=1600&quality=90&mode=crop']
    , ['China', 'Yangshuo', 'Yangshuo, a county and resort town in southern China’s Guangxi region, is known for its dramatic karst mountain landscape and outdoor recreation. The town is set amid pinnacles like Bilian Feng (Green Lotus Peak), which has a hiking trail to the top. Tour boats offer cruises on the Li River past picturesque countryside from the town of Guilin to the north.', 'https://en.wikipedia.org/wiki/Yangshuo_County', 'https://studycli.org/wp-content/uploads/2021/06/Yangshuo-Guilin-River-Scene.jpg']
    , ['United States', 'Yellowstone National Park', "Yellowstone National Park is a nearly 3,500-sq.-mile wilderness recreation area atop a volcanic hot spot. Mostly in Wyoming, the park spreads into parts of Montana and Idaho too. Yellowstone features dramatic canyons, alpine rivers, lush forests, hot springs and gushing geysers, including its most famous, Old Faithful. It's also home to hundreds of animal species, including bears, wolves, bison, elk and antelope.", 'https://en.wikipedia.org/wiki/Yellowstone_National_Park', 'https://media.cntraveler.com/photos/61fc35a8e227a2ac8c5797a4/16:9/w_2560%2Cc_limit/The%2520Grand%2520Canyon%2520of%2520the%2520Yellowstone%2C%2520as%2520seen%2520from%2520Artist%2520Point_CREDIT%2520Navid%2520Baraty_navidbaraty-yellowstone-1.jpg']
    , ['United Kingdom', 'York Minster', 'The Cathedral and Metropolitical Church of Saint Peter in York, commonly known as York Minster, is the cathedral of York, North Yorkshire, England, and is one of the largest of its kind in Northern Europe.', 'https://en.wikipedia.org/wiki/York_Minster', 'https://www.historyhit.com/app/uploads/2020/07/1920px-York_Minster_31310135538-1.jpg']
    , ['United States', 'Yosemite National Park', 'Yosemite National Park is in California’s Sierra Nevada mountains. It’s famed for its giant, ancient sequoia trees, and for Tunnel View, the iconic vista of towering Bridalveil Fall and the granite cliffs of El Capitan and Half Dome. In Yosemite Village are shops, restaurants, lodging, the Yosemite Museum and the Ansel Adams Gallery, with prints of the photographer’s renowned black-and-white landscapes of the area.', 'https://en.wikipedia.org/wiki/Yosemite_National_Park', 'https://www.history.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTU3ODc4NjAwMjkxNzIyNTY5/yosemite-3.jpg']
    , ['Mexico', 'Yucatán Peninsula', "The Yucatán Peninsula separates the Gulf of Mexico from the Caribbean Sea, encompassing 3 Mexican states, plus portions of Belize and Guatemala. On the Caribbean, Mexico's Riviera Maya resort strip is bookended by 2 popular destinations: Cancún, with its high-rise hotels and nightlife, and, down the coast, quieter Tulum, a rare seaside example of the Mayan ruins found throughout the peninsula's interior.", 'https://en.wikipedia.org/wiki/Yucatán_Peninsula', 'https://cdn.britannica.com/11/93011-050-2CA5CA55/Hotel-Zone-barrier-island-causeway-city-Caribbean.jpg']
    , ['Zanzibar', 'Zanzibar', 'Zanzibar is a Tanzanian archipelago off the coast of East Africa. On its main island, Unguja, familiarly called Zanzibar, is Stone Town, a historic trade center with Swahili and Islamic influences. Its winding lanes present minarets, carved doorways and 19th-century landmarks such as the House of Wonders, a former sultan’s palace. The northern villages Nungwi and Kendwa have wide beaches lined with hotels.', 'https://en.wikipedia.org/wiki/Zanzibar', 'https://www.african-adventures.co.uk/wp-content/uploads/2021/05/Stone-Town-1140x700.png']
    , ['United States', 'Zion National Park', 'Zion National Park is a southwest Utah nature preserve distinguished by Zion Canyon’s steep red cliffs. Zion Canyon Scenic Drive cuts through its main section, leading to forest trails along the Virgin River. The river flows to the Emerald Pools, which have waterfalls and a hanging garden. Also along the river, partly through deep chasms, is Zion Narrows wading hike.', 'https://en.wikipedia.org/wiki/Zion_National_Park', 'http://res.cloudinary.com/simpleview/image/upload/v1601421684/clients/utahddm/_66d4d4c3-5ff8-416b-8ee4-fe462a5a40aa.2576c93235.jpg']
    , ['Mexico', 'Zócalo', 'The Zócalo is the common name of the main square in central Mexico City. Prior to the colonial period, it was the main ceremonial center in the Aztec city of Tenochtitlan. The plaza used to be known simply as the "Main Square" or "Arms Square", and today its formal name is Plaza de la Constitución.', 'https://en.wikipedia.org/wiki/Zócalo', 'https://theculturetrip.com/wp-content/uploads/2016/09/388271879_be5d5cae7f_o.jpg']
    ];


places.push(oneHundreds);
places.push(twoHundreds);
console.log(places);
// select random place and get the image address
function changeImage() {
    indexLine = Math.floor(Math.random() * 100);
    indexDatabase = Math.floor(Math.random() * 2);

   document.getElementById("Img1").src = places[indexDatabase][indexLine][4];
   document.getElementById('countryName').innerHTML = places[indexDatabase][indexLine][0];
   document.getElementById('landmarkName').innerHTML = places[indexDatabase][indexLine][1];
   document.getElementById('landmarkDesc').innerHTML = places[indexDatabase][indexLine][2];
   document.getElementById('descSource').innerHTML = places[indexDatabase][indexLine][3];
}

function changePage() {
    
   setTimeout(function(){
    indexLine = Math.floor(Math.random() * 100);
    indexDatabase = Math.floor(Math.random() * 2);
   location.href = 'placeDetail.html';

    }, 1500); 
    
}

function goHome() {
    location.href = 'website.html';
}



window.onload = changeImage();

